# The URL the site will be built for
base_url = "http://localhost:1111"
description = "A site for showcasing projects."
author = "Dave Wang (Ru Han Wang)"
theme = "project-portfolio"

taxonomies = [
    {name = "projects", paginate_by = 5, feed = true},
    {name = "skills", paginate_by = 5, feed = true},
]

[extra]
home = "Home"
projects = "Projects"
skills = "Skills"
read_more = "Read More"
skills_technologies = "Skills & Technologies"
main_skills = "Main Skills"
other_skills = "Additional Skills"
menu_items = [
    { name = "Projects", url = "/projects/" },
    { name = "About", url = "/about/" }
]

[extra.navbar]
title = "Project Portfolio"

[extra.index]
title = "Welcome to My Cloud Portfolio!"
slogan = """With a Master of Engineering in AI, I have technical and business know-how of large-scale data 
analytics and machine learning. This portfolio site serves to show you the value I can deliver to your 
organization's cloud computing needs."""
image = "portrait.png"
image_alt = "I have experience with data science, ML, and cloud computing."

[extra.social]
machine_learning_portfolio = "https://www.davesportfolio.tech"
github = "https://github.com/ruhan-dave"
gitlab = "https://gitlab.com/ruhan-dave"
linkedin = "https://www.linkedin.com/in/ruhan-wang-3b946b175/"
email = "dave.wang@duke.edu"
